import CatCard from '@/components/cards/cat/CatCard';
import BaseTemplate from '@/components/templates/base/BaseTemplate';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BaseTemplate sampleTextProp="Hello world!" />
        <CatCard
          author="Alex"
          body="Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi perferendis molestiae non nemo doloribus. Doloremque, nihil! At ea atque quidem!"
          tag="Felines"
          time="2h ago"
          title="What's new in Cats"
        />
      </main>
    </>
  );
}
